version: "3.8"

volumes:
  mysql57:
    name: mysql57
  mysql57conf:
    name: mysql57conf # docker run -it -v mysql57conf:/app --rm busybox

services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: asdf
      MYSQL_DATABASE: monitor
    volumes:
      - mysql57:/var/lib/mysql
      - mysql57conf:/etc/mysql/conf.d

  # GUI: http://localhost:8025
  #mail:
  #  image: mailhog/mailhog:latest
  #  ports:
  #    - 1025:1025
  #    - 8025:8025

