version: "3.8"

services:
  monitor:
    build: ./httpd/
    container_name: phplaravel_monitor
    ports:
      - "${HTTP_PORT}:80"
    environment:
      VIRTUALHOST: ${VIRTUALHOST}
    volumes:
      - "./httpd/php-laravel-monitor:/var/www/html"
    networks:
      - web_monitor
      - postgresql_monitor
      - selenium_monitor
    #restart: always

  pgsql:
    container_name: postgresql_monitor
    image: postgres:13
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      PGPASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - "./postgresql:/var/lib/postgresql/data"
    networks:
      - postgresql_monitor
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "monitor", "-U", "postgres"]
    #restart: always

  pgadmin:
    container_name: pgadmin_monitor
    image: dpage/pgadmin4
    depends_on:
      - pgsql
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - "./pgadmin:/root/.pgadmin"
    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - postgresql_monitor
    #restart: always

  selenium-hub:
    container_name: selenium_monitor
    image: selenium/hub:4.0.0-rc-1-prerelease-20210823
    depends_on:
      - monitor
    environment:
      - logger.level=DEBUG
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - selenium_monitor

  chrome:
    container_name: chrome_monitor
    image: selenium/node-chrome:4.0.0-rc-1-prerelease-20210823
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - logger.level=DEBUG
    ports:
      - "6900:5900"
    networks:
      - selenium_monitor
      - web_monitor
    extra_hosts:
      - "monitor.com.ve:172.26.0.2"

#  firefox:
#    container_name: firefox_monitor
#    image: selenium/node-firefox:4.0.0-rc-1-prerelease-20210823
#   shm_size: 2gb
#    depends_on:
#      - selenium-hub
#    environment:
#      - SE_EVENT_BUS_HOST=selenium-hub
#     - SE_EVENT_BUS_PUBLISH_PORT=4442
#      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
#    ports:
#      - "6902:5900"
#    networks:
#      - selenium_monitor


networks:
  web_monitor:
    external: true
  postgresql_monitor:
    external: true
  selenium_monitor:
    external: true
